model:
  trf_heads: 1
  fusion_heads: 1
  trf_layers: 1
  fusion_layers: 1
  trf_feedforward: 1024
  trf_dropout: 0.3
  emb: 128
  num_classes: 4
  max_burst_num: 100
  temperature: 0.3
  alpha: 0.4
  update_pretrain_params: true
  use_segment_embedding: true
  use_position_embedding: true
  use_feature_segment_embedding: true
  shuffle_data: true
  name: "mmnet_{dataset}"
  mode: "pretrain"
  lambda_mlm: 0.0

data:
  pad_num: 10
  pad_len: 400
  packet_sequence_num: 100
  burst_sequence_num: 50
  pcaket_features_num: 2
  burst_features_num: 4
  n_vocab: 261
  Serial_features: true
  Parallel_feature: false
  dataset: ""

training:
  seed: 42
  learning_rate: 0.001
  epoch: 100
  batch_size: 32
  require_improvement: 10000
  contrastive_weight: 0.5
  k: 10
  freeze_feature_extractors: false

path:
  vocab_path: '/Config/vocab.txt'
  pretrain_path: "/Model/pretrain/{dataset}/"
  pretrained_model_path: ""
  train_path: "/TrafficData/{dataset}/mmnet/{dataset}_train.txt"
  test_path: "/TrafficData/{dataset}/mmnet/{dataset}_test.txt"
  label_path: "/TrafficData/{dataset}/mmnet/{dataset}_label.txt"
  finetune_train_path: "/TrafficData/{dataset}/mmnet/{dataset}_fusion_train.txt"
  finetune_test_path: "/TrafficData/{dataset}/mmnet/{dataset}_fusion_test.txt"
  save_path: "/Model/contrastive/save"
  cache_path: "/TrafficData/DataCache/"

device:
  device: "cuda:0"
  queue_size: 65536
  momentum: 0.995
  alpha: 0.4,,image.png
